### DISCUSSION TITLE
App sees a router address for all IP addresses instead of their real addresses

### DISCUSSION THREAD

**Discussion by suprovsky** [rustdesk/rustdesk-server-pro#521] [General]
I use RustDesk Pro behind a reverse proxy (Nginx) with the following configuration:
rustdesk.example.local
```
server {
    listen 80;
    server_name rustdesk.example.local;
    return 302 https://rustdesk.example.local$request_uri;
}

server {
    listen 443 ssl;
    server_name rustdesk.example.local;

    ssl_certificate /etc/ssl/private/asterisk-example.crt;
    ssl_certificate_key /etc/ssl/private/asterisk-example.key;
    ssl_dhparam /etc/nginx/dhparam.pem;

    location / {
        proxy_pass http://127.0.0.1:21114;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600;
        proxy_connect_timeout 3600;
    }
}
```
docker-compose.yml
```
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server-pro:latest
    environment:
      - ALWAYS_USE_RELAY=Y
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped
    pull_policy: always

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
    pull_policy: always
```
Regardless, all of the machines I have in my network show up as 192.168.4.1 (the Docker host is 192.168.4.5).
![Image](https://github.com/user-attachments/assets/f6d2b9cb-9a14-4e2d-980b-84e28e8707f0)
