### DISCUSSION TITLE
license already in use by another machine

### DISCUSSION THREAD

**Discussion by rustdesk** [rustdesk/rustdesk-server-pro#94] [Q&A]
please go here for machine migration https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/license/#invoices-license-retrieval-and-migration

you usually encountered this issue if you run  pro in docker without `network_mode: "host"`, please follow our tutorial correctly.
https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/installscript/docker/

**Comment by yaroz** [comment]
Good afternoon.  We get this error at least twice a week.  I have to unbind it and re-associate every time.  I've ensured that my docker-compose.yml matches the tutorial.

```
`version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"
    environment:
      - ALWAYS_USE_RELAY=Y
    depends_on:
      - hbbr
    restart: unless-stopped


  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ALWAYS_USE_RELAY=Y`
  ```

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/installscript/docker/

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/fe319d27-988f-42e5-8fee-81bca5e31072)

**Reply by yaroz** [reply]
@rustdesk Did you look at the docker-compose I posted?  I've had that all along, but still get the error a couple times a week.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/20463573/f2e8444a-9d80-4b80-b627-ae2aeb87a633)

**Reply by rustdesk** [reply]
You can confirm if your `host` settings really work by checking if your hostname and ip are the same as your physical machine.

 https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/license/#invoices-license-retrieval-and-migration

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/9f89e8ca-bed2-45eb-889c-db8c259980bf)

**Reply by yaroz** [reply]
It shows the external IP, not the host IP.

**Reply by rustdesk** [reply]
external IP is expected.

**Reply by rustdesk** [reply]
How about hostname?

**Reply by yaroz** [reply]
hostname is correct.. it shows as "docker", which is the name of the host, not the container.

**Reply by rustdesk** [reply]
What os are you using?

**Reply by yaroz** [reply]
ubuntu 22.04.3

**Reply by rustdesk** [reply]
Wierd, I run `docker compose up -d` repeatly, all work fine. I will dig more.

**Reply by rustdesk** [reply]
I put a fix on our side, let us know if you still have problem several days later.

**Reply by yaroz** [reply]
Thank you.

**Comment by HugeFrog24** [comment]
I found a workaround without needing `network_mode: "host"` (which wouldn't work for my setup with nginx-proxy-manager anyway).

Container logs reveal the issue:

```bash
# Initial container status
$ docker ps | grep rust
63f61c938ad6   rustdesk/rustdesk-server-pro:latest   "hbbs"   13 minutes ago   Up 13 minutes   hbbs
8cad973f424a   rustdesk/rustdesk-server-pro:latest   "hbbr"   13 minutes ago   Up 13 minutes   hbbr

# Restart containers
$ docker compose down && docker compose up -d

# New container status
$ docker ps | grep rust
0f550056f716   rustdesk/rustdesk-server-pro:latest   "hbbs"   3 seconds ago   Up 2 seconds   hbbs
f747be2c032a   rustdesk/rustdesk-server-pro:latest   "hbbr"   3 seconds ago   Up 3 seconds   hbbr
```

It seems the license might be tied to container hostnames. Docker assigns random container IDs on each restart, which previously invalidated the license. By adding a stable hostname to the containers, the license would remain valid:

```yaml
services:
  hbbs:
    hostname: rustdesk-server-hbbs  # Stable hostname
    networks:
      - nginx-proxy-manager_npm-network
    # ... rest of config ...
  hbbr:
    hostname: rustdesk-server-hbbr  # Stable hostname
    networks:
      - nginx-proxy-manager_npm-network
    # ... rest of config ...
networks:
  nginx-proxy-manager_npm-network:
    external: true
```

This worked for me - I can restart the containers and the license sticks around. Might be helpful for others who need to run their setup behind a reverse proxy!
