### ISSUE TITLE
Unable to validate license (400 Bad request)

### ISSUE THREAD

**Issue by mistial-dev** [rustdesk/rustdesk-server-pro#136]
When attempting to install the license, I am getting the error `Failed to update license: server error: 400 Bad Request`.

Installation is done by docker-compose, with the following configuration:
```yaml
version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped


  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
```
