### ISSUE TITLE
Issues with Docker

### ISSUE THREAD

**Issue by dinger1986** [rustdesk/rustdesk-server-pro#25]
Every time the docker container is updated/changed/recreated it is requiring me to unbind the license and rebind. this has been reported by 2 users now

**Comment by rustdesk** [comment]
License stored in the database, they have not mounted volume correctly. Please follow tutorial strictly.

https://rustdesk.com/docs/en/self-host/install/#install-your-own-server-with-docker-compose

**Comment by dinger1986** [comment]
thanks, will feed this back and see if it resolves the issue

**Comment by dinger1986** [comment]
Yes, was thinking I should spin it up soon, I have used it alot in the past just prefer vms

**Comment by dinger1986** [comment]
fired up docker and it all came back :)

made docker-compose.yml
```
version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21114:21114
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbs
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
```

The license persists over docker down and docker up but after a reboot of the host the license then says its in use by another device. the db is getting written and the time stamp is changing.
